### ISSUE TITLE
Add "Need Help" button at the top of the brainiak homepage

### ISSUE THREAD

**Issue by manojneuro** [brainiak/brainiak.github.io#21]
Hi,

Currently the "Need Help" button is embedded towards the bottom of the brainiak Home page. It would make it easier for users to know where to log issues etc. to see the link on top.

Thanks,
Manoj

**Comment by danielsuo** [comment]
@mihaic We should have a think about what we want as top-level links more generally. For example, events doesn't seem like a great link to have. Link to the GitHub repo does.

@manojneuro is a link called "Help" ok? Need help is a bit long.

**Comment by mihaic** [comment]
Events looks to me like news, so I think we should have it displayed prominently, especially if we increase the frequency of the events.

Please add a GitHub link too.

**Comment by danielsuo** [comment]
Jon specifically wanted to separate Events and News.

I'll update Help and GitHub
