### ISSUE TITLE
Conda install instructions

### ISSUE THREAD

**Issue by manojneuro** [brainiak/brainiak.github.io#22]
On the brainiak homepage http://brainiak.org, instructions for conda install have not been added under "Getting Started".

**Comment by danielsuo** [comment]
Manoj: what instructions have you provided to students? We can put the
battle-tested instructions up.

**Comment by danielsuo** [comment]
Ok, how's this (also tagging @mihaic):

1. Install Conda (link to windows, mac, linux)
2. Create Conda environment (conda create --n venv)
3. Activate Conda environment (windows: activate venv; mac / linux: source
activate venv)
4. Install Brainiak

conda install -c brainiak -c defaults -c conda-forge brainiak

**Comment by manojneuro** [comment]
Looks great.

Manoj

**Comment by manojneuro** [comment]
@danielsuo Looks great. Please also modify this text "Install via Docker or pip" to include condo. Thanks.

**Comment by danielsuo** [comment]
Good catch! I'll fix.
