### ISSUE TITLE
Add HTTPS

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak.github.io#23]
HTTPS is now supported by GitHub:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by danielsuo** [comment]
Pointed A records to updated IP addresses. GitHub is generating new certificates for us. Three additional steps to take

- [ ] Check the "Enforce HTTPS" box in the settings page
- [ ] Find-replace all "http://" with "https://"
- [ ] Check that nothing's (too) broken

**Comment by danielsuo** [comment]
@mihaic Want to check this out and see if it's working to your expectation?

**Comment by mihaic** [comment]
Looks great! Thanks, @danielsuo.
